# STAT40800 Data Programming with Python
## Jake Mac Uilliam



# Week 2

## Control flow

Control flow refers to the order in which your code is run. You may only want to run certain sections of your code provided a particular condition is met (`if`), you may want to run a section multiple times (`for`) or you may want to repeat section until a particular condition is violated (`while`). Understanding control flow is essential for computer scientists.

### `if` statements
An `if` statement contains a Boolean condition followed by some consequent action. The action will only be carried out if the condition is met. See example below for the syntax. The `if` statement and condition must be followed by a colon `:`.

In [1]:
y = 4
z = 0
if y<3:
    z = 2
print(z)

0


Try changing y to 4 and see what happens.

**Note** the indentation of `z = 2`. This is very important! Python uses indentations to specify what is/isn't part of the if statement. This will also be the case will `for` and `while` loops. If we were to also indent the print statement, `z` would only be displayed if the condition `y<3` was met.

Often there are multiple conditions, with different consequent actions. For this we can extend the if statement with `elif` and `else` statements. An `elif` (else if) statement, like an `if` statement, requires a Boolean condition and the consequent action is carried out if the condition is met, provided all none of the previous conditions were met. An `else` statement does not have a Boolean condition, its consequent action is carried out if none of the previous conditions were met.

In [ ]:
x = 0
if x > 0:
    print('x is positive')
elif x < 0:
    print('x is negative')
else:
    print('x is zero')

Try changing the value of x to obtained each of the possible outcomes

**Note:** Only one set of actions can be carried out per `if/elif/else` statement. When a condition is met and the associated actions implemented, we skip to the end of the `if/elif/else` statement.

In [ ]:
p = 7
if p>3:
    q = 3
elif p>1:
    q = 1
else:
    q = 0
print(q)

Even though p is also greater than 1, we do not get to the `elif` statement because the `if` statement was satisfied. If you change p to 2, you should obtain q = 1

#### Exercise 1

A souvenir store in Venice is selling magnets for €3.00 each. However, they offer discounts such that the more you buy the cheaper they are.
If you buy 10 or more magnets they cost €2.00 each, or if you buy more than 5 but less than 10 they cost €2.50 each. Write a set of `if/elif/else` statements to calculate the total cost of the order for $n$ magnets. Set $n=3$, $n=6$, and $n=10$ to confirm that you get the correct answer..

In [5]:
# n=3
# n=6
n=10

if n<=5 and n>0:
    c= 3
elif n>5 and n<10:
    c=2.5
elif n>=10:
    c= 2

print(c)

2


### `for` loops

Often we want to loop over a set of commands multiple times. This is what a `for` loop is used for. Typically, we change one of the variable each time we run the section of code.

Below we set `i` equal to 1 and execute the commands inside the `for` loop (indented code). Then we set `i` equal to 2 and repeat and continue this process until we each the last value in the list.

In [ ]:
sum1 = 0
list1 = [1,2,3,4,5,6,7,8,9,10]
for i in list1:
    sum1 = sum1 + i 
print(sum1)

We can use `range` to specify the range in which the index is varying without the need of explicitly writing down a list.

In [ ]:
sum1 = 0
for i in range(1,11):
    sum1 = sum1 + i
print(sum1)

We often combine `if` statements and `for` loops:

In [ ]:
for i in list1:
    if i%2 == 0:    # `%` is the modulo operator, i.e. a%b is the remainder of a divided by b. 
        print(i,' is even')
    else:
        print(i,' is odd')

**Note:** When asking if two objects are equal, we must use the double equals operator `==`. A single equal sign `=` is used for assigning values to objects. For not equal we use `!=`.

#### Exercise 2 

Write a `for` loop to calculate the sum of $x^2$ for $x$ from 0 to 9, $\sum_{x=0}^9 x^2$.

In [7]:
s=0
for i in range(0,10):
    x=i*i
    s=s+x

print('sum of x^2 for x from 0 to 9 :',s)

# print(1+4+9+16+25+36+49+64+81)

sum of x^2 for x from 0 to 9 : 285
285


### `while` loops

`while` loops are similar to `for` loops except they contain a Boolean condition rather than a list of values to cycle through. The section of code inside the `while` loop is repeated until the Boolean condition is not longer true. It is important that you ensure your condition can be met, otherwise your code will continue forever. 

__TIP:__ Press `i` twice to stop the Python interpreter if you accidentally create a never-ending loop (`Ctrl` + `c` for most other IDEs).

In [ ]:
x = 0
while x<10:
    x += 1   # shorthand for x = x + 1
    print(x)

#### Exercise 3

Alter your `for` loop from Exercise 2 to a `while` loop, which again calculates $\sum_{x=0} x^2$, but terminates instead when the sum is greater 500. 

In [8]:
s=0
i=0
while s<=500:
   x=i*i 
   s= s+ x
   i+=1

print(f"sum of square of number from 0 to {i} is {s}")

sum of square of number from 0 to 12 is 506


## Functions

A function is simply an input-output relationship, e.g. $f(x) = x^2$, if we use the input $x = 2$, we get an output $4$, which of course is $2^2$. Similarly, in programming, we specify a set of inputs and commands to be carried of on those inputs and the function returns a set of outputs.

In Python, a function is defined using `def`. The function is given a name and its inputs are specified in round brackets after the function name. Typically, a function must have a return statement, which specifies the function output. Below we create a function `f`, which returns the input `x` to the power of 2:

In [ ]:
def f(x):
    result = x**2 #or pow(x,2)
    return result
print(f(4))

Functions can have more than one input or output:

In [ ]:
def addition(x,y):
    return x+y
print(addition(2,3))
def add_and_sub(x,y):
    return x+y, x-y
print(add_and_sub(2,3))

Combining this with some of the things from the previous section, we can write a function that returns all of the odd numbers up to a particular number:

In [ ]:
def odd_numbers(n):
    nums = []
    i = 1
    while i<n:
        if i%2 != 0:
            nums.append(i)
        i += 1
    return nums

In [ ]:
print(odd_numbers(10))

We can also stored the output of the function and apply other methods to it

In [ ]:
output = odd_numbers(10)
output.append(11)
print(output)
output.remove(3)
print(output)

#### Exercise 4
Write a function *factorial* to compute the factorial of $x$. The input argument should be $x$ and the function should return $x!$. For example, the factorial of 5, $5! = 5\times 4 \times 3\times 2 \times 1 = 120$

In [18]:
def fact(x):
    fact=1
    for i in range(1,x+1,1):
        fact=fact*i
        print(fact)
    print(f"factorial of {x} is {fact}")

print(fact(5))

1
2
6
24
120
factorial of 5 is 120
None


## Modules and Packages
### Modules
A module is simply a collection of functions that can be imported and used within your Python environment. 

I have created an example module (*my_module.py*), which can be downloaded from Brightspace. Save the module in the same working directory as your Python notebook so that you can easily load it into your Python environment.

Modules are loaded into your current Python environment with an `import` statement. To import a module, simply type *import* followed by the module name.

In [19]:
import my_module

To use the functions within a module use the syntax `module.function()`

In [20]:
my_module.odd_numbers()

1
3
5
7
9


If we need to use lots of functions we can include a shortcut in the import statement.

In [21]:
import my_module as mm
mm.even_numbers(8)

2
4
6
8


If we only want to use a couple of functions from a module, it may make more sense to import the functions individually, rather than importing the full module, especially if there are a lot of functions in the module.

In [22]:
from my_module import odd_numbers
odd_numbers(5)

1
3
5


**Note:** We don't include the module prefix when a function is imported individually.

### Packages
A package is a collection of modules, arranged in a directory structure. We will be using lots of different packages over the course of this trimester. The main ones we will use are **NumPy** and **pandas**. 

Packages are imported in the same way as modules.

In [23]:
import numpy as np
print(np.cos(0.5))

0.8775825618903728


 Most of the packages we will be using are already installed in Jupyter Notebook. However, should you need to install a package, use the following code:

`import sys
!{sys.executable} -m pip install <package_name>`

where `<package_name>` is the name of the package you wish to install.

## NumPy
NumPy is a very useful package that offers four main components:
* Vectors, matrices, and multi-dimensional arrays
* Vectorised calculations which avoid unnecessary loops
* Lots of mathematical commands useful for statistical modelling
* Entry points for C/C++/Fortran code 

As shown above NumPy is typically imported with the shortcut `np`.

In [ ]:
import numpy as np

### Vectors
It is easy to create a **vector** (1D arrays) using the NumPy `array` function.

In [24]:
my_data = range(10)
my_array = np.array(my_data)
print(my_array)
print(type(my_array))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


Operations performed on arrays are *vectorised*. For example, if we add a number to an array, it is added to every element in that array.

In [25]:
print(my_array+2)
print(my_array*4)

[ 2  3  4  5  6  7  8  9 10 11]
[ 0  4  8 12 16 20 24 28 32 36]


When we multiple an array by an array the corresponding elements are multiplied, i.e. the first element in one array is multiplied by the first element in the other array, the second by the second, etc. Hence, the two arrays must be the same size.

In [26]:
print(my_array*my_array)
print(my_array*range(3,13))

[ 0  1  4  9 16 25 36 49 64 81]
[  0   4  10  18  28  40  54  70  88 108]


A NumPy array, like many Python objects, has attributes associated with it, such as `dtype` (the type of data stored in a NumPy array). To access an attribute of an array, use the syntax `array_name.attribute`.


In [27]:
print(my_array.dtype)

int32


**Note:** The syntax is similar to applying a method, but an attribute doesn't have arguments, so we don't include brackets after the attribute name.

#### Exercise 5
Write a function *multiples_three* that creates and returns a 1D NumPy array with the first *n* multiples of 3, where *n* is the function input.

In [30]:

mylist=[]
def multiple_three(n):
    for i in range(1,n+1):
        mylist.append(i*3)
        print(mylist)

    op=np.array(mylist)
    print(op)

print(multiple_three(5))

[3]
[3, 6]
[3, 6, 9]
[3, 6, 9, 12]
[3, 6, 9, 12, 15]
[ 3  6  9 12 15]
None


### 2D arrays
Multi-dimensional arrays can be created by specifying a nested list or tuple. We will focus only on 2D arrays.

In [31]:
my_array_2 = np.array([range(0,5),[10]*5])
print(my_array_2)

[[ 0  1  2  3  4]
 [10 10 10 10 10]]


Some useful attributes for multi-dimensional arrays are `ndim`, `shape`, and `size`. Run the code below to see these attributes for our 2D array.

In [32]:
print(my_array_2.ndim)
print(my_array_2.shape)
print(my_array_2.size)

2
(2, 5)
10


Arrays are indexed in a similar way to lists and tuples. However, for a multi-dimensional array, there is an index for each dimension. For a 2D array, the first index is the row and the second is the column `[row,column]`. 


In [33]:
print(my_array_2[1,3])

10


**Remember** indexing in Python starts at zero, so the first entry in the second second row of a 2D array would have an index `[1,0]'

We can create arrays of zeros or ones with the commands below. The first argument is the number of rows we wish the array to have, and the second is the number of columns.

In [34]:
print(np.zeros((5,6)))
print(np.ones((10,2)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### Exercise 6
Write a function *matrix_index* that returns the entry in the *n*th row and *m*th column of a matrix *X*. The function inputs should be *X*, *n* and *m* (in that order).
For example, if $$X = \begin{pmatrix} 7 & 3 \\ 1 & 9 \end{pmatrix},$$ `matrix_index(X,0,1)` should return 3.

In [43]:

def matrix_index(X,n,m):
    r=X[n,m]
    print(r)

X=([7,3],[1,9])
X=np.array(X)
print(X)
print(matrix_index(X,0,1))

[[7 3]
 [1 9]]
3
None
